/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_projects;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Abhishek
 */
public class DisplayForm extends javax.swing.JFrame
{
    String username;
    /**
     * Creates new form PrintForm
     */
    public DisplayForm()
    {
        /*initComponents();
        addWindowListener(new WindowClose(new MenuClass(username)));
        displayName(username);
        showImage(username);*/
    }
    
    public DisplayForm(String username)
    {
        this.username = username;
        initComponents();
        addWindowListener(new WindowClose(new MenuClass(username)));
        displayName(username);
        showImage(username);
    }
    
    public void displayName(String username)
    {
        try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/database", "root", "root");
            PreparedStatement ps = con.prepareStatement("Select * from database.formdata where user = '" + username + "'");
            ResultSet rs = ps.executeQuery();
            if(rs.next())
            {
                txtname.setText(rs.getString("firstname") + " " + rs.getString("middlename") + " " + rs.getString("lastname"));
                txtname.setEditable(false);
                setLabelText(txtmoname,"mothername",rs);
                setLabelText(txtage,"age",rs);
                setLabelText(txtgen,"gen",rs);
                setLabelText(txtdob,"dob",rs);
                setLabelText(txtno,"mobno",rs);
                setLabelText(txteno,"emno",rs);
                setLabelText(txtboard,"preboard",rs);
                setLabelText(txtgrade,"grade", rs);
                setLabelText(txtyear,"passyear",rs);
                setLabelText(txtstream,"passstream",rs);
                txtadd.setText(rs.getString("address"));
                txtadd.setEditable(false);
            }
        }
        catch (SQLException ex)
        {
            ex.printStackTrace();
        }
    }
    
    public void setLabelText(JTextField txt, String s, ResultSet rs) throws SQLException
    {
        txt.setText(rs.getString(s));
        txt.setEditable(false);
    }
    
    public void showImage(String username)
    {
        try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/database", "root", "root");
            PreparedStatement ps = con.prepareStatement("Select * from database.photodata where user = '" + username + "'");
            ResultSet rs = ps.executeQuery();
            if(rs.next())
            {
                byte[] img = rs.getBytes("photo");
                displayImage2(lblphoto,img);
                byte[] im = rs.getBytes("sign");
                displayImage2(lblsign,im);
            }
        }
        catch (SQLException ex)
        {
            ex.printStackTrace();
        }
    }
    
    public void displayImage2(JLabel lbl,byte[] image)
    {
        ImageIcon ic = new ImageIcon(image);
        Image img = ic.getImage();
        Image newimg = img.getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon im = new ImageIcon(newimg);
        lbl.setIcon(im);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        scrlpane = new javax.swing.JScrollPane();
        pnlframe = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlshow = new javax.swing.JPanel();
        lblphoto = new javax.swing.JLabel();
        lblsign = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtadd = new javax.swing.JTextArea();
        txtname = new javax.swing.JTextField();
        txtmoname = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtdob = new javax.swing.JTextField();
        txtgen = new javax.swing.JTextField();
        txtno = new javax.swing.JTextField();
        txteno = new javax.swing.JTextField();
        pnlshow1 = new javax.swing.JPanel();
        lblboard = new javax.swing.JLabel();
        lblstream = new javax.swing.JLabel();
        lblyear = new javax.swing.JLabel();
        txtboard = new javax.swing.JTextField();
        txtyear = new javax.swing.JTextField();
        txtstream = new javax.swing.JTextField();
        txtgrade = new javax.swing.JTextField();
        lblgrade = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        scrlpane.setPreferredSize(new java.awt.Dimension(800, 1200));

        pnlframe.setBackground(new java.awt.Color(204, 255, 255));
        pnlframe.setPreferredSize(new java.awt.Dimension(800, 1200));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STUDENT DETAIL'S");
        jLabel1.setOpaque(true);

        pnlshow.setBackground(new java.awt.Color(204, 255, 204));
        pnlshow.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 5), "PERSONAL INFORMATION :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 25), new java.awt.Color(0, 102, 102))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Student Name : ");
        jLabel2.setPreferredSize(new java.awt.Dimension(450, 60));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Mother's Name : ");
        jLabel3.setPreferredSize(new java.awt.Dimension(450, 60));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Student Age : ");
        jLabel4.setPreferredSize(new java.awt.Dimension(450, 60));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("D.O.B. :");
        jLabel5.setPreferredSize(new java.awt.Dimension(450, 60));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Student Gender :");
        jLabel6.setPreferredSize(new java.awt.Dimension(450, 60));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Emergency Contact No. :");
        jLabel7.setPreferredSize(new java.awt.Dimension(450, 60));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Contact No. :");
        jLabel8.setPreferredSize(new java.awt.Dimension(450, 60));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Address :");
        jLabel9.setPreferredSize(new java.awt.Dimension(450, 60));

        txtadd.setBackground(new java.awt.Color(204, 255, 204));
        txtadd.setColumns(20);
        txtadd.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        txtadd.setRows(5);
        txtadd.setAutoscrolls(false);
        txtadd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane1.setViewportView(txtadd);

        txtname.setBackground(new java.awt.Color(204, 255, 204));
        txtname.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        txtname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtmoname.setBackground(new java.awt.Color(204, 255, 204));
        txtmoname.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        txtmoname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtage.setBackground(new java.awt.Color(204, 255, 204));
        txtage.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        txtage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtdob.setBackground(new java.awt.Color(204, 255, 204));
        txtdob.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        txtdob.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtgen.setBackground(new java.awt.Color(204, 255, 204));
        txtgen.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        txtgen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtno.setBackground(new java.awt.Color(204, 255, 204));
        txtno.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        txtno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txteno.setBackground(new java.awt.Color(204, 255, 204));
        txteno.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        txteno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout pnlshowLayout = new javax.swing.GroupLayout(pnlshow);
        pnlshow.setLayout(pnlshowLayout);
        pnlshowLayout.setHorizontalGroup(
            pnlshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlshowLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlshowLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlshowLayout.createSequentialGroup()
                        .addGroup(pnlshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblsign, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlshowLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlshowLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmoname, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnlshowLayout.createSequentialGroup()
                        .addGroup(pnlshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtno, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txteno, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgen, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnlshowLayout.setVerticalGroup(
            pnlshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlshowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlshowLayout.createSequentialGroup()
                        .addComponent(lblphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblsign, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlshowLayout.createSequentialGroup()
                        .addGroup(pnlshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmoname, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pnlshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgen, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtno, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txteno, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlshow1.setBackground(new java.awt.Color(204, 255, 204));
        pnlshow1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 5), "ACADEMIC INFORMATION :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 25), new java.awt.Color(0, 102, 102))); // NOI18N

        lblboard.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        lblboard.setForeground(new java.awt.Color(0, 102, 102));
        lblboard.setText("Previous Board :");
        lblboard.setPreferredSize(new java.awt.Dimension(450, 50));

        lblstream.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        lblstream.setForeground(new java.awt.Color(0, 102, 102));
        lblstream.setText("Previous Stream :");
        lblstream.setPreferredSize(new java.awt.Dimension(450, 50));

        lblyear.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        lblyear.setForeground(new java.awt.Color(0, 102, 102));
        lblyear.setText("Passing Year :");
        lblyear.setPreferredSize(new java.awt.Dimension(450, 50));

        txtboard.setBackground(new java.awt.Color(204, 255, 204));
        txtboard.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        txtboard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtyear.setBackground(new java.awt.Color(204, 255, 204));
        txtyear.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        txtyear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtstream.setBackground(new java.awt.Color(204, 255, 204));
        txtstream.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        txtstream.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtgrade.setBackground(new java.awt.Color(204, 255, 204));
        txtgrade.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        txtgrade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblgrade.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        lblgrade.setForeground(new java.awt.Color(0, 102, 102));
        lblgrade.setText("Grade :");
        lblgrade.setPreferredSize(new java.awt.Dimension(450, 50));

        javax.swing.GroupLayout pnlshow1Layout = new javax.swing.GroupLayout(pnlshow1);
        pnlshow1.setLayout(pnlshow1Layout);
        pnlshow1Layout.setHorizontalGroup(
            pnlshow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlshow1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlshow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblgrade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlshow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblstream, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(lblyear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(lblboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                .addGap(26, 26, 26)
                .addGroup(pnlshow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtboard, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtstream, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        pnlshow1Layout.setVerticalGroup(
            pnlshow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlshow1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlshow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblboard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtboard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlshow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlshow1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblyear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlshow1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlshow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstream, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtstream, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlshow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlframeLayout = new javax.swing.GroupLayout(pnlframe);
        pnlframe.setLayout(pnlframeLayout);
        pnlframeLayout.setHorizontalGroup(
            pnlframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlframeLayout.createSequentialGroup()
                .addGroup(pnlframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlshow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlframeLayout.createSequentialGroup()
                            .addGap(174, 174, 174)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlframeLayout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(pnlshow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlframeLayout.setVerticalGroup(
            pnlframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlframeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlshow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlshow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scrlpane.setViewportView(pnlframe);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrlpane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrlpane, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(DisplayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(DisplayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(DisplayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(DisplayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new DisplayForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblboard;
    private javax.swing.JLabel lblgrade;
    private javax.swing.JLabel lblphoto;
    private javax.swing.JLabel lblsign;
    private javax.swing.JLabel lblstream;
    private javax.swing.JLabel lblyear;
    private javax.swing.JPanel pnlframe;
    private javax.swing.JPanel pnlshow;
    private javax.swing.JPanel pnlshow1;
    private javax.swing.JScrollPane scrlpane;
    private javax.swing.JTextArea txtadd;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtboard;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txteno;
    private javax.swing.JTextField txtgen;
    private javax.swing.JTextField txtgrade;
    private javax.swing.JTextField txtmoname;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtno;
    private javax.swing.JTextField txtstream;
    private javax.swing.JTextField txtyear;
    // End of variables declaration//GEN-END:variables
}
