/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_projects;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Abhishek
 */
public class FillForm extends javax.swing.JFrame 
{
    String usern;
    /**
     * Creates new form MyFourthForm
     */
    public FillForm() 
    {
        /*initComponents();
        addWindowListener(new WindowClose(new MenuClass(usern)));*/
    }
    
    public FillForm(String usern) 
    {
        initComponents();
        this.usern = usern;
        addWindowListener(new WindowClose(new MenuClass(usern)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btngrpgender = new javax.swing.ButtonGroup();
        scrpaneframe = new javax.swing.JScrollPane();
        pnlframe = new javax.swing.JPanel();
        lbltitle = new javax.swing.JLabel();
        pnlpersonal = new javax.swing.JPanel();
        lblfname = new javax.swing.JLabel();
        lblmname = new javax.swing.JLabel();
        lbllname = new javax.swing.JLabel();
        lbldob = new javax.swing.JLabel();
        lbladdress = new javax.swing.JLabel();
        lblgender = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        mname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        combodate = new javax.swing.JComboBox<>();
        combomonth = new javax.swing.JComboBox<>();
        comboyear = new javax.swing.JComboBox<>();
        rbtnmale = new javax.swing.JRadioButton();
        rbtnfemale = new javax.swing.JRadioButton();
        rbtnother = new javax.swing.JRadioButton();
        scrpaneaddress = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        lblmno = new javax.swing.JLabel();
        moname = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        lblage = new javax.swing.JLabel();
        lblmoname = new javax.swing.JLabel();
        lbleno = new javax.swing.JLabel();
        mobno = new javax.swing.JTextField();
        eno = new javax.swing.JTextField();
        lblage1 = new javax.swing.JLabel();
        lblmsgnum = new javax.swing.JLabel();
        pnlacademic = new javax.swing.JPanel();
        lblpy = new javax.swing.JLabel();
        lblgrade = new javax.swing.JLabel();
        lblps = new javax.swing.JLabel();
        lblpay = new javax.swing.JLabel();
        comboboard = new javax.swing.JComboBox<>();
        combopassyear = new javax.swing.JComboBox<>();
        combostream = new javax.swing.JComboBox<>();
        combograde = new javax.swing.JComboBox<>();
        btnsubmit = new javax.swing.JButton();
        lblmsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(800, 1000));

        scrpaneframe.setBackground(new java.awt.Color(204, 255, 204));
        scrpaneframe.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        scrpaneframe.setPreferredSize(new java.awt.Dimension(820, 1200));

        pnlframe.setBackground(new java.awt.Color(204, 255, 204));
        pnlframe.setPreferredSize(new java.awt.Dimension(800, 1200));

        lbltitle.setBackground(new java.awt.Color(0, 255, 204));
        lbltitle.setFont(new java.awt.Font("Agency FB", 1, 35)); // NOI18N
        lbltitle.setForeground(new java.awt.Color(0, 102, 102));
        lbltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle.setText("REGISTRATION FORM");
        lbltitle.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 51)));
        lbltitle.setOpaque(true);
        lbltitle.setPreferredSize(new java.awt.Dimension(200, 40));

        pnlpersonal.setBackground(new java.awt.Color(153, 255, 255));
        pnlpersonal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "ENTER PERSONAL INFORMATION : ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Agency FB", 1, 30), new java.awt.Color(0, 51, 102))); // NOI18N
        pnlpersonal.setAlignmentX(1.0F);
        pnlpersonal.setAlignmentY(1.0F);
        pnlpersonal.setPreferredSize(new java.awt.Dimension(750, 600));

        lblfname.setBackground(new java.awt.Color(0, 255, 204));
        lblfname.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lblfname.setForeground(new java.awt.Color(0, 102, 102));
        lblfname.setText(" FIRST NAME : ");
        lblfname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lblfname.setPreferredSize(new java.awt.Dimension(150, 30));

        lblmname.setBackground(new java.awt.Color(0, 255, 204));
        lblmname.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lblmname.setForeground(new java.awt.Color(0, 102, 102));
        lblmname.setText(" MIDDLE NAME : ");
        lblmname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lblmname.setPreferredSize(new java.awt.Dimension(150, 30));

        lbllname.setBackground(new java.awt.Color(0, 255, 204));
        lbllname.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbllname.setForeground(new java.awt.Color(0, 102, 102));
        lbllname.setText(" LAST NAME : ");
        lbllname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lbllname.setPreferredSize(new java.awt.Dimension(150, 30));

        lbldob.setBackground(new java.awt.Color(0, 255, 204));
        lbldob.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbldob.setForeground(new java.awt.Color(0, 102, 102));
        lbldob.setText(" DATE OF BIRTH : ");
        lbldob.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lbldob.setPreferredSize(new java.awt.Dimension(150, 30));

        lbladdress.setBackground(new java.awt.Color(0, 255, 204));
        lbladdress.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbladdress.setForeground(new java.awt.Color(0, 102, 102));
        lbladdress.setText(" ADDRESS : ");
        lbladdress.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lbladdress.setPreferredSize(new java.awt.Dimension(150, 30));

        lblgender.setBackground(new java.awt.Color(0, 255, 204));
        lblgender.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lblgender.setForeground(new java.awt.Color(0, 102, 102));
        lblgender.setText(" GENDER : ");
        lblgender.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lblgender.setPreferredSize(new java.awt.Dimension(150, 30));

        fname.setBackground(new java.awt.Color(0, 255, 204));
        fname.setFont(new java.awt.Font("Agency FB", 1, 25)); // NOI18N
        fname.setForeground(new java.awt.Color(0, 102, 102));
        fname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fname.setPreferredSize(new java.awt.Dimension(500, 35));

        mname.setBackground(new java.awt.Color(0, 255, 204));
        mname.setFont(new java.awt.Font("Agency FB", 1, 25)); // NOI18N
        mname.setForeground(new java.awt.Color(0, 102, 102));
        mname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        mname.setPreferredSize(new java.awt.Dimension(500, 35));

        lname.setBackground(new java.awt.Color(0, 255, 204));
        lname.setFont(new java.awt.Font("Agency FB", 1, 25)); // NOI18N
        lname.setForeground(new java.awt.Color(0, 102, 102));
        lname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lname.setPreferredSize(new java.awt.Dimension(500, 35));

        combodate.setBackground(new java.awt.Color(0, 255, 204));
        combodate.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        combodate.setForeground(new java.awt.Color(0, 102, 102));
        combodate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DD", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        combodate.setPreferredSize(new java.awt.Dimension(60, 30));

        combomonth.setBackground(new java.awt.Color(0, 255, 204));
        combomonth.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        combomonth.setForeground(new java.awt.Color(0, 102, 102));
        combomonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MM", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        combomonth.setPreferredSize(new java.awt.Dimension(60, 30));

        comboyear.setBackground(new java.awt.Color(0, 255, 204));
        comboyear.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        comboyear.setForeground(new java.awt.Color(0, 102, 102));
        comboyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YYYY", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        comboyear.setPreferredSize(new java.awt.Dimension(50, 30));

        rbtnmale.setBackground(new java.awt.Color(0, 255, 204));
        btngrpgender.add(rbtnmale);
        rbtnmale.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        rbtnmale.setForeground(new java.awt.Color(0, 102, 102));
        rbtnmale.setText("MALE");
        rbtnmale.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rbtnmale.setMaximumSize(new java.awt.Dimension(100, 30));
        rbtnmale.setMinimumSize(new java.awt.Dimension(100, 30));
        rbtnmale.setPreferredSize(new java.awt.Dimension(100, 30));

        rbtnfemale.setBackground(new java.awt.Color(0, 255, 204));
        btngrpgender.add(rbtnfemale);
        rbtnfemale.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        rbtnfemale.setForeground(new java.awt.Color(0, 102, 102));
        rbtnfemale.setText("FEMALE");
        rbtnfemale.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rbtnfemale.setMaximumSize(new java.awt.Dimension(100, 30));
        rbtnfemale.setMinimumSize(new java.awt.Dimension(100, 30));
        rbtnfemale.setPreferredSize(new java.awt.Dimension(100, 30));

        rbtnother.setBackground(new java.awt.Color(0, 255, 204));
        btngrpgender.add(rbtnother);
        rbtnother.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        rbtnother.setForeground(new java.awt.Color(0, 102, 102));
        rbtnother.setText("OTHER");
        rbtnother.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rbtnother.setMaximumSize(new java.awt.Dimension(100, 30));
        rbtnother.setMinimumSize(new java.awt.Dimension(100, 30));
        rbtnother.setPreferredSize(new java.awt.Dimension(100, 30));

        txtaddress.setBackground(new java.awt.Color(0, 255, 204));
        txtaddress.setColumns(20);
        txtaddress.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        txtaddress.setForeground(new java.awt.Color(0, 102, 102));
        txtaddress.setRows(5);
        scrpaneaddress.setViewportView(txtaddress);

        lblmno.setBackground(new java.awt.Color(0, 255, 204));
        lblmno.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lblmno.setForeground(new java.awt.Color(0, 102, 102));
        lblmno.setText(" MOBILE NO.: ");
        lblmno.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lblmno.setPreferredSize(new java.awt.Dimension(150, 30));

        moname.setBackground(new java.awt.Color(0, 255, 204));
        moname.setFont(new java.awt.Font("Agency FB", 1, 25)); // NOI18N
        moname.setForeground(new java.awt.Color(0, 102, 102));
        moname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        moname.setPreferredSize(new java.awt.Dimension(500, 35));

        age.setBackground(new java.awt.Color(0, 255, 204));
        age.setFont(new java.awt.Font("Agency FB", 1, 25)); // NOI18N
        age.setForeground(new java.awt.Color(0, 102, 102));
        age.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        age.setPreferredSize(new java.awt.Dimension(500, 35));
        age.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                ageKeyPressed(evt);
            }
        });

        lblage.setBackground(new java.awt.Color(0, 255, 204));
        lblage.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lblage.setForeground(new java.awt.Color(0, 102, 102));
        lblage.setText(" AGE : ");
        lblage.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lblage.setPreferredSize(new java.awt.Dimension(150, 30));

        lblmoname.setBackground(new java.awt.Color(0, 255, 204));
        lblmoname.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lblmoname.setForeground(new java.awt.Color(0, 102, 102));
        lblmoname.setText(" MOTHER'S NAME : ");
        lblmoname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lblmoname.setPreferredSize(new java.awt.Dimension(150, 30));

        lbleno.setBackground(new java.awt.Color(0, 255, 204));
        lbleno.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbleno.setForeground(new java.awt.Color(0, 102, 102));
        lbleno.setText(" EMERGENCY NO.:");
        lbleno.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lbleno.setPreferredSize(new java.awt.Dimension(150, 30));

        mobno.setBackground(new java.awt.Color(0, 255, 204));
        mobno.setFont(new java.awt.Font("Agency FB", 1, 25)); // NOI18N
        mobno.setForeground(new java.awt.Color(0, 102, 102));
        mobno.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        mobno.setPreferredSize(new java.awt.Dimension(500, 35));
        mobno.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                mobnoKeyPressed(evt);
            }
        });

        eno.setBackground(new java.awt.Color(0, 255, 204));
        eno.setFont(new java.awt.Font("Agency FB", 1, 25)); // NOI18N
        eno.setForeground(new java.awt.Color(0, 102, 102));
        eno.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        eno.setPreferredSize(new java.awt.Dimension(500, 35));
        eno.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                enoKeyPressed(evt);
            }
        });

        lblage1.setBackground(new java.awt.Color(0, 255, 204));
        lblage1.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lblage1.setForeground(new java.awt.Color(0, 102, 102));
        lblage1.setText("YR(S)");
        lblage1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lblage1.setPreferredSize(new java.awt.Dimension(150, 30));

        lblmsgnum.setBackground(new java.awt.Color(255, 255, 255));
        lblmsgnum.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lblmsgnum.setForeground(new java.awt.Color(255, 0, 0));
        lblmsgnum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlpersonalLayout = new javax.swing.GroupLayout(pnlpersonal);
        pnlpersonal.setLayout(pnlpersonalLayout);
        pnlpersonalLayout.setHorizontalGroup(
            pnlpersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpersonalLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlpersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlpersonalLayout.createSequentialGroup()
                        .addComponent(lbladdress, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrpaneaddress))
                    .addGroup(pnlpersonalLayout.createSequentialGroup()
                        .addGroup(pnlpersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlpersonalLayout.createSequentialGroup()
                                .addComponent(lbldob, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combodate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(combomonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboyear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlpersonalLayout.createSequentialGroup()
                                .addComponent(lblgender, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnmale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(rbtnfemale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(rbtnother, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlpersonalLayout.createSequentialGroup()
                                .addGroup(pnlpersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblmoname, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(lblage, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(lblmno, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(lbleno, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(lbllname, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(lblmname, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(lblfname, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlpersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(mobno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(moname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(eno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlpersonalLayout.createSequentialGroup()
                                        .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblage1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblmsgnum, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        pnlpersonalLayout.setVerticalGroup(
            pnlpersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpersonalLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlpersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fname, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(lblfname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlpersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mname, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(lblmname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlpersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlpersonalLayout.createSequentialGroup()
                        .addComponent(lname, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(pnlpersonalLayout.createSequentialGroup()
                        .addComponent(lbllname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(pnlpersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(moname, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(lblmoname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlpersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(age, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(lblage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmsgnum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlpersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mobno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlpersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eno, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(lbleno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlpersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(combodate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlpersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(combomonth, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboyear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbldob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlpersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnmale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnfemale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnother, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlpersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbladdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrpaneaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlacademic.setBackground(new java.awt.Color(153, 255, 255));
        pnlacademic.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "ENTER ACADEMIC DETAILS: ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Agency FB", 1, 30), new java.awt.Color(0, 51, 102))); // NOI18N
        pnlacademic.setAlignmentX(1.0F);
        pnlacademic.setAlignmentY(1.0F);
        pnlacademic.setPreferredSize(new java.awt.Dimension(750, 600));

        lblpy.setBackground(new java.awt.Color(0, 255, 204));
        lblpy.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lblpy.setForeground(new java.awt.Color(0, 102, 102));
        lblpy.setText(" PREVIOUS BOARD : ");
        lblpy.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lblpy.setPreferredSize(new java.awt.Dimension(150, 30));

        lblgrade.setBackground(new java.awt.Color(0, 255, 204));
        lblgrade.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lblgrade.setForeground(new java.awt.Color(0, 102, 102));
        lblgrade.setText(" GRADE : ");
        lblgrade.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lblgrade.setPreferredSize(new java.awt.Dimension(150, 30));

        lblps.setBackground(new java.awt.Color(0, 255, 204));
        lblps.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lblps.setForeground(new java.awt.Color(0, 102, 102));
        lblps.setText(" PREVIOUS STREAM : ");
        lblps.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lblps.setPreferredSize(new java.awt.Dimension(150, 30));

        lblpay.setBackground(new java.awt.Color(0, 255, 204));
        lblpay.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lblpay.setForeground(new java.awt.Color(0, 102, 102));
        lblpay.setText(" PASSING YEAR : ");
        lblpay.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lblpay.setPreferredSize(new java.awt.Dimension(150, 30));

        comboboard.setBackground(new java.awt.Color(0, 255, 204));
        comboboard.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        comboboard.setForeground(new java.awt.Color(0, 102, 102));
        comboboard.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "HSC", "CBSE ", "ICSE", "OTHER " }));
        comboboard.setPreferredSize(new java.awt.Dimension(60, 30));

        combopassyear.setBackground(new java.awt.Color(0, 255, 204));
        combopassyear.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        combopassyear.setForeground(new java.awt.Color(0, 102, 102));
        combopassyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YYYY", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        combopassyear.setPreferredSize(new java.awt.Dimension(50, 30));

        combostream.setBackground(new java.awt.Color(0, 255, 204));
        combostream.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        combostream.setForeground(new java.awt.Color(0, 102, 102));
        combostream.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "SCIENCE (PCMB) IT", "SCIENCE (PCMB) CS", "SCIENCE (PCMB) ENTC", "SCIENCE (PCM) IT", "SCIENCE (PCM) CS", "SCIENCE (PCM) ENTC" }));
        combostream.setPreferredSize(new java.awt.Dimension(60, 30));

        combograde.setBackground(new java.awt.Color(0, 255, 204));
        combograde.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        combograde.setForeground(new java.awt.Color(0, 102, 102));
        combograde.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "A1", "A2", "B1", "B2", "C1", "C2", "D1", "D2", "P", "FAIL" }));
        combograde.setPreferredSize(new java.awt.Dimension(50, 30));

        btnsubmit.setBackground(new java.awt.Color(0, 153, 153));
        btnsubmit.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        btnsubmit.setForeground(new java.awt.Color(0, 102, 102));
        btnsubmit.setText("SUBMIT");
        btnsubmit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsubmit.setPreferredSize(new java.awt.Dimension(100, 40));
        btnsubmit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnsubmitActionPerformed(evt);
            }
        });

        lblmsg.setBackground(new java.awt.Color(255, 255, 255));
        lblmsg.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lblmsg.setForeground(new java.awt.Color(255, 0, 0));
        lblmsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlacademicLayout = new javax.swing.GroupLayout(pnlacademic);
        pnlacademic.setLayout(pnlacademicLayout);
        pnlacademicLayout.setHorizontalGroup(
            pnlacademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlacademicLayout.createSequentialGroup()
                .addGap(0, 264, Short.MAX_VALUE)
                .addComponent(lblmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
            .addGroup(pnlacademicLayout.createSequentialGroup()
                .addGroup(pnlacademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlacademicLayout.createSequentialGroup()
                        .addGroup(pnlacademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblpay, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlacademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlacademicLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lblps, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlacademicLayout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addGroup(pnlacademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblpy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(28, 28, 28)
                        .addGroup(pnlacademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combopassyear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combostream, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboboard, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combograde, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlacademicLayout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlacademicLayout.setVerticalGroup(
            pnlacademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlacademicLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlacademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpy, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboboard, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlacademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combopassyear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlacademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblps, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combostream, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlacademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combograde, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlframeLayout = new javax.swing.GroupLayout(pnlframe);
        pnlframe.setLayout(pnlframeLayout);
        pnlframeLayout.setHorizontalGroup(
            pnlframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlframeLayout.createSequentialGroup()
                .addGroup(pnlframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlacademic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlframeLayout.createSequentialGroup()
                            .addGap(275, 275, 275)
                            .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlframeLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(pnlpersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlframeLayout.setVerticalGroup(
            pnlframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlframeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlpersonal, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(pnlacademic, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        scrpaneframe.setViewportView(pnlframe);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrpaneframe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrpaneframe, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        scrpaneframe.getAccessibleContext().setAccessibleParent(this);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mobnoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_mobnoKeyPressed
    {//GEN-HEADEREND:event_mobnoKeyPressed
        char ch = evt.getKeyChar();
        if(Character.isAlphabetic(ch))
        {
           mobno.setEditable(false);
           lblmsgnum.setText("Enter Numerical Value Only");
           lblmsgnum.setOpaque(true);
        }
        else
        {
            mobno.setEditable(true);
            lblmsgnum.setText("");
            lblmsgnum.setOpaque(false);
        }
    }//GEN-LAST:event_mobnoKeyPressed

    private void enoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_enoKeyPressed
    {//GEN-HEADEREND:event_enoKeyPressed
        char ch = evt.getKeyChar();
        if(Character.isLetter(ch))
        {
           eno.setEditable(false);
           lblmsgnum.setText("Enter Numerical Value Only");
           lblmsgnum.setOpaque(true);
        }
        else
        {
            eno.setEditable(true);
            lblmsgnum.setText("");
            lblmsgnum.setOpaque(false);
        }
    }//GEN-LAST:event_enoKeyPressed

    private void ageKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_ageKeyPressed
    {//GEN-HEADEREND:event_ageKeyPressed
        char ch = evt.getKeyChar();
        if(Character.isLetter(ch))
        {
           age.setEditable(false);
           lblmsgnum.setText("Enter Numerical Value Only");
           lblmsgnum.setOpaque(true);
        }
        else
        {
            age.setEditable(true);
            lblmsgnum.setText("");
            lblmsgnum.setOpaque(false);
        }
    }//GEN-LAST:event_ageKeyPressed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnsubmitActionPerformed
    {//GEN-HEADEREND:event_btnsubmitActionPerformed
        if(fname.getText().isEmpty() | mname.getText().isEmpty() | lname.getText().isEmpty() | moname.getText().isEmpty() | age.getText().isEmpty() | mobno.getText().isEmpty() | eno.getText().isEmpty() | txtaddress.getText().isEmpty() | btngrpgender.getSelection() == null | combodate.getSelectedIndex() == 0 | combomonth.getSelectedIndex() == 0 | comboyear.getSelectedIndex() == 0 | comboboard.getSelectedIndex()== 0 | combograde.getSelectedIndex() == 0 | combopassyear.getSelectedIndex() == 0 | combostream.getSelectedIndex() == 0)
        {
            lblmsg.setText("Field(s) are Empty");
            lblmsg.setOpaque(true);
            
        }
        else
        {
            lblmsg.setText("");
            lblmsg.setOpaque(false);
           
            String gender = null;
            if(rbtnmale.isSelected())
            {
                gender = "Male";
            }
            else if(rbtnfemale.isSelected())
            {
                gender = "Female";
            }
            else if(rbtnother.isSelected())
            {
                gender = "other";
            }
            
            int flag = 0,res;
            res = JOptionPane.showConfirmDialog(null,"You Won't be able to make Changes Further!", "Are You Sure You Want To Submit?", JOptionPane.YES_NO_CANCEL_OPTION);
            if(res == JOptionPane.YES_OPTION)
            {
                try
                {
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/database","root","root");
                    Statement st = con.createStatement();
                    String query;
                    query = "Insert into database.formdata (firstname,middlename,lastname,mothername,age,mobno,emno,dob,gen,address,preboard,passstream,passyear,grade,user) " +
                          "values ('" + fname.getText().trim() + "','" + mname.getText().trim() + "','" + lname.getText().trim() + "','" + moname.getText().trim() + "','" + age.getText().trim() + "','" + mobno.getText().trim() + "','" + eno.getText().trim() + "','" + (String)combodate.getSelectedItem() + "/" + (String)combomonth.getSelectedItem() + "/" + (String)comboyear.getSelectedItem() + "','" + gender + "','" + txtaddress.getText().trim() + "','" + (String)comboboard.getSelectedItem() + "','" + combostream.getSelectedItem() + "','" + combopassyear.getSelectedItem() + "','" + combograde.getSelectedItem() + "','" + usern + "')";
                    st.executeUpdate(query);
                    JOptionPane.showMessageDialog(null, "Submitted Successfully");
                }
                catch(SQLException ex)
                {
                    JOptionPane.showMessageDialog(null, "Error When Submitting " + ex);
                    ex.printStackTrace();
                    flag = 1;
                }
                if(flag == 0)
                {
                    new MenuClass(usern).setVisible(true);
                    dispose();
                }
            }
        }
    }//GEN-LAST:event_btnsubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FillForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.ButtonGroup btngrpgender;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JComboBox<String> comboboard;
    private javax.swing.JComboBox<String> combodate;
    private javax.swing.JComboBox<String> combograde;
    private javax.swing.JComboBox<String> combomonth;
    private javax.swing.JComboBox<String> combopassyear;
    private javax.swing.JComboBox<String> combostream;
    private javax.swing.JComboBox<String> comboyear;
    private javax.swing.JTextField eno;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblage1;
    private javax.swing.JLabel lbldob;
    private javax.swing.JLabel lbleno;
    private javax.swing.JLabel lblfname;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblgrade;
    private javax.swing.JLabel lbllname;
    private javax.swing.JLabel lblmname;
    private javax.swing.JLabel lblmno;
    private javax.swing.JLabel lblmoname;
    private javax.swing.JLabel lblmsg;
    private javax.swing.JLabel lblmsgnum;
    private javax.swing.JLabel lblpay;
    private javax.swing.JLabel lblps;
    private javax.swing.JLabel lblpy;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mname;
    private javax.swing.JTextField mobno;
    private javax.swing.JTextField moname;
    private javax.swing.JPanel pnlacademic;
    private javax.swing.JPanel pnlframe;
    private javax.swing.JPanel pnlpersonal;
    private javax.swing.JRadioButton rbtnfemale;
    private javax.swing.JRadioButton rbtnmale;
    private javax.swing.JRadioButton rbtnother;
    private javax.swing.JScrollPane scrpaneaddress;
    private javax.swing.JScrollPane scrpaneframe;
    private javax.swing.JTextArea txtaddress;
    // End of variables declaration//GEN-END:variables
}
