/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_projects;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Abhishek
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form MyThirdframe
     */
    public LoginFrame() 
    {
        initComponents();
        displayImage(lblclose,"F:\\Regal JAVA\\AWT & SWING\\Java_Projects\\images\\Actions-window-close-icon.png");
        displayImage(lblsignin,"F:\\Regal JAVA\\AWT & SWING\\Java_Projects\\images\\login.jpg");
    }
    
    public void displayImage(JLabel lbl,String path)
    {
        ImageIcon ic = new ImageIcon(path);
        Image img = ic.getImage();
        Image newimg = img.getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon im = new ImageIcon(newimg);
        lbl.setIcon(im);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel2 = new javax.swing.JPanel();
        pnlframe = new javax.swing.JPanel();
        pnllogin = new javax.swing.JPanel();
        lbllogin = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        lbluser = new javax.swing.JLabel();
        lblpass = new javax.swing.JLabel();
        passfield = new javax.swing.JPasswordField();
        lblsignin = new javax.swing.JLabel();
        btnforgotpass = new javax.swing.JButton();
        btnsignup = new javax.swing.JButton();
        lblclose = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(0, 0, 600, 400));
        setUndecorated(true);

        pnlframe.setBackground(new java.awt.Color(204, 204, 204));
        pnlframe.setPreferredSize(new java.awt.Dimension(600, 400));

        pnllogin.setBackground(new java.awt.Color(255, 255, 255));
        pnllogin.setFocusable(false);
        pnllogin.setPreferredSize(new java.awt.Dimension(300, 250));
        pnllogin.setRequestFocusEnabled(false);
        pnllogin.setVerifyInputWhenFocusTarget(false);

        lbllogin.setBackground(new java.awt.Color(204, 204, 204));
        lbllogin.setFont(new java.awt.Font("Californian FB", 1, 25)); // NOI18N
        lbllogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogin.setText("APPLICANT LOGIN HERE");
        lbllogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbllogin.setOpaque(true);
        lbllogin.setPreferredSize(new java.awt.Dimension(280, 40));

        txtuser.setBackground(new java.awt.Color(204, 204, 204));
        txtuser.setFont(new java.awt.Font("Californian FB", 0, 20)); // NOI18N
        txtuser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtuser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtuser.setPreferredSize(new java.awt.Dimension(200, 30));

        lbluser.setFont(new java.awt.Font("Californian FB", 0, 20)); // NOI18N
        lbluser.setForeground(new java.awt.Color(102, 102, 102));
        lbluser.setText("username");
        lbluser.setPreferredSize(new java.awt.Dimension(40, 30));

        lblpass.setFont(new java.awt.Font("Californian FB", 0, 20)); // NOI18N
        lblpass.setForeground(new java.awt.Color(102, 102, 102));
        lblpass.setText("password");
        lblpass.setPreferredSize(new java.awt.Dimension(40, 30));

        passfield.setBackground(new java.awt.Color(204, 204, 204));
        passfield.setFont(new java.awt.Font("Californian FB", 0, 20)); // NOI18N
        passfield.setToolTipText("");
        passfield.setPreferredSize(new java.awt.Dimension(200, 30));

        lblsignin.setBackground(new java.awt.Color(255, 0, 0));
        lblsignin.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblsigninMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlloginLayout = new javax.swing.GroupLayout(pnllogin);
        pnllogin.setLayout(pnlloginLayout);
        pnlloginLayout.setHorizontalGroup(
            pnlloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlloginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblsignin, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(pnlloginLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnlloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbllogin, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlloginLayout.createSequentialGroup()
                        .addGroup(pnlloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblpass, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(lbluser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        pnlloginLayout.setVerticalGroup(
            pnlloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlloginLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbllogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbluser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblsignin, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnforgotpass.setBackground(new java.awt.Color(204, 204, 204));
        btnforgotpass.setFont(new java.awt.Font("Californian FB", 0, 20)); // NOI18N
        btnforgotpass.setText("forgot password?");
        btnforgotpass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnforgotpass.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnforgotpass.setOpaque(false);
        btnforgotpass.setPreferredSize(new java.awt.Dimension(150, 40));
        btnforgotpass.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnforgotpassActionPerformed(evt);
            }
        });

        btnsignup.setBackground(new java.awt.Color(204, 204, 204));
        btnsignup.setFont(new java.awt.Font("Californian FB", 0, 20)); // NOI18N
        btnsignup.setText("SIGN UP");
        btnsignup.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnsignup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsignup.setOpaque(false);
        btnsignup.setPreferredSize(new java.awt.Dimension(100, 40));
        btnsignup.setSelected(true);
        btnsignup.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnsignupActionPerformed(evt);
            }
        });

        lblclose.setPreferredSize(new java.awt.Dimension(40, 40));
        lblclose.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblcloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlframeLayout = new javax.swing.GroupLayout(pnlframe);
        pnlframe.setLayout(pnlframeLayout);
        pnlframeLayout.setHorizontalGroup(
            pnlframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlframeLayout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(pnlframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlframeLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnforgotpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnsignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnllogin, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(lblclose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlframeLayout.setVerticalGroup(
            pnlframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlframeLayout.createSequentialGroup()
                .addGroup(pnlframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlframeLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(pnllogin, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlframeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblclose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(pnlframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnforgotpass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlframe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlframe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblsigninMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblsigninMouseClicked
    {//GEN-HEADEREND:event_lblsigninMouseClicked
        try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/database", "root", "root");
            Statement st = con.createStatement();
            ResultSet rs;
            String query = "Select * from database.login where uname = '" + txtuser.getText() + "' and passw = '" + new String(passfield.getPassword()) + "'";
            rs = st.executeQuery(query);
            if(rs.next())
            {
                if(txtuser.getText().equals(rs.getString("uname")) &  new String(passfield.getPassword()).equals(rs.getString("passw")))
                {
                    new MenuClass(txtuser.getText()).setVisible(true);
                    dispose();
                    JOptionPane.showMessageDialog(null, "Logged in Successfully");
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Enter Valid Login ID or Password");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Enter Valid Login ID or Password");
            }
        }
        catch(SQLException ex)
        {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_lblsigninMouseClicked

    private void lblcloseMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblcloseMouseClicked
    {//GEN-HEADEREND:event_lblcloseMouseClicked
        int res = JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Close?", "Close Window", JOptionPane.YES_NO_CANCEL_OPTION);
        if(res == JOptionPane.YES_OPTION)
        {
            dispose();
        }
    }//GEN-LAST:event_lblcloseMouseClicked

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnsignupActionPerformed
    {//GEN-HEADEREND:event_btnsignupActionPerformed
        new SignUpClass().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnsignupActionPerformed

    private void btnforgotpassActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnforgotpassActionPerformed
    {//GEN-HEADEREND:event_btnforgotpassActionPerformed
        new ForgotPasswordClass().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnforgotpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnforgotpass;
    private javax.swing.JButton btnsignup;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblclose;
    private javax.swing.JLabel lbllogin;
    private javax.swing.JLabel lblpass;
    private javax.swing.JLabel lblsignin;
    private javax.swing.JLabel lbluser;
    private javax.swing.JPasswordField passfield;
    private javax.swing.JPanel pnlframe;
    private javax.swing.JPanel pnllogin;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
