/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_projects;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Abhishek
 */
public class MenuClass extends javax.swing.JFrame implements Runnable
{
    String ref;
    boolean thrstop;
    /**
     * Creates new form MenuClass
     */
    public MenuClass()
    {
        /*initComponents();
        displayImage(lbllogout,"F:\\JAVA\\AWT\\Java_Projects\\images\\logout.jpg");
        displayImage(lblpnl,"F:\\JAVA\\AWT\\Java_Projects\\images\\background.jpg");
        lblwelcome.setText("WELCOME " + ref + " ");
        thrstop = true;
        new Thread(this).start();
        displayName(ref);
        showImage(ref);*/
    }
    
    public MenuClass(String ref)
    {
        initComponents();
        this.ref = ref;
        displayImage(lbllogout,"F:\\Regal JAVA\\AWT & SWING\\Java_Projects\\images\\logout.jpg");
        displayImage(lblpnl,"F:\\Regal JAVA\\AWT & SWING\\Java_Projects\\images\\background.jpg");
        lblwelcome.setText("WELCOME " + ref + " ");
        thrstop = true;
        new Thread(this).start();
        displayName(ref);
        showImage(ref);
    }
    
    public void displayName(String username)
    {
        try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/database", "root", "root");
            PreparedStatement ps = con.prepareStatement("Select * from database.formdata where user = '" + username + "'");
            ResultSet rs = ps.executeQuery();
            if(rs.next())
            {
                lblname.setText(rs.getString("firstname") + " " + rs.getString("middlename") + " " + rs.getString("lastname"));
            }
        }
        catch (SQLException ex)
        {
            ex.printStackTrace();
        }
    }
    
    public void showImage(String username)
    {
        try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/database", "root", "root");
            PreparedStatement ps = con.prepareStatement("Select * from database.photodata where user = '" + username + "'");
            ResultSet rs = ps.executeQuery();
            if(rs.next())
            {
                byte[] img = rs.getBytes("photo");
                displayImage2(lblprofilephoto,img);
                byte[] im = rs.getBytes("sign");
                displayImage2(lblsignature,im);
            }
        }
        catch (SQLException ex)
        {
            ex.printStackTrace();
        }
    }
    
    public void displayImage2(JLabel lbl,byte[] image)
    {
        ImageIcon ic = new ImageIcon(image);
        Image img = ic.getImage();
        Image newimg = img.getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon im = new ImageIcon(newimg);
        lbl.setIcon(im);
    }
    
    public void displayImage(JLabel lbl,String path)
    {
        ImageIcon ic = new ImageIcon(path);
        Image img = ic.getImage();
        Image newimg = img.getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon im = new ImageIcon(newimg);
        lbl.setIcon(im);
    }
    
    public void run()
    {
        while(thrstop)
        {
            try
            {
                Thread.sleep(300);
            }
            catch(InterruptedException e)
            {
            }
            char ch;
            String str;
            ch = lblwelcome.getText().charAt(lblwelcome.getText().length() - 1);
            str = lblwelcome.getText().substring(0,lblwelcome.getText().length() - 1);
            str = ch + str;
            lblwelcome.setText(str);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnlframe = new javax.swing.JPanel();
        lbllogout = new javax.swing.JLabel();
        pnlphoto = new javax.swing.JPanel();
        lblprofilephoto = new javax.swing.JLabel();
        lblsignature = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        pnldata = new javax.swing.JPanel();
        lblupphoto1 = new javax.swing.JLabel();
        lblchpass = new javax.swing.JLabel();
        lblupphoto = new javax.swing.JLabel();
        lblupphoto2 = new javax.swing.JLabel();
        btnform = new javax.swing.JButton();
        btnphoto = new javax.swing.JButton();
        btnpass = new javax.swing.JButton();
        btnview = new javax.swing.JButton();
        lblwelcome = new javax.swing.JLabel();
        lblpnl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlframe.setBackground(new java.awt.Color(255, 255, 255));
        pnlframe.setOpaque(false);
        pnlframe.setPreferredSize(new java.awt.Dimension(900, 600));
        pnlframe.setLayout(null);

        lbllogout.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lbllogoutMouseClicked(evt);
            }
        });
        pnlframe.add(lbllogout);
        lbllogout.setBounds(810, 15, 70, 70);

        pnlphoto.setOpaque(false);

        lblsignature.setPreferredSize(new java.awt.Dimension(300, 100));

        lblname.setBackground(new java.awt.Color(255, 102, 255));
        lblname.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        lblname.setForeground(new java.awt.Color(255, 255, 255));
        lblname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblname.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblname.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblname.setPreferredSize(new java.awt.Dimension(300, 40));

        javax.swing.GroupLayout pnlphotoLayout = new javax.swing.GroupLayout(pnlphoto);
        pnlphoto.setLayout(pnlphotoLayout);
        pnlphotoLayout.setHorizontalGroup(
            pnlphotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlphotoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlphotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlphotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblprofilephoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblsignature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnlphotoLayout.setVerticalGroup(
            pnlphotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlphotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblprofilephoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblsignature, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        pnlframe.add(pnlphoto);
        pnlphoto.setBounds(531, 105, 349, 464);

        pnldata.setOpaque(false);

        lblupphoto1.setBackground(new java.awt.Color(255, 51, 255));
        lblupphoto1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lblupphoto1.setForeground(new java.awt.Color(102, 0, 102));
        lblupphoto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblupphoto1.setText("To Fill Registration Form");
        lblupphoto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblupphoto1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblupphoto1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblupphoto1.setOpaque(true);
        lblupphoto1.setPreferredSize(new java.awt.Dimension(280, 50));

        lblchpass.setBackground(new java.awt.Color(255, 51, 255));
        lblchpass.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lblchpass.setForeground(new java.awt.Color(102, 0, 102));
        lblchpass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblchpass.setText("To Change Password");
        lblchpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblchpass.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblchpass.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblchpass.setOpaque(true);
        lblchpass.setPreferredSize(new java.awt.Dimension(280, 50));

        lblupphoto.setBackground(new java.awt.Color(255, 51, 255));
        lblupphoto.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lblupphoto.setForeground(new java.awt.Color(102, 0, 102));
        lblupphoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblupphoto.setText("To Upload Photo and Signature");
        lblupphoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblupphoto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblupphoto.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblupphoto.setOpaque(true);
        lblupphoto.setPreferredSize(new java.awt.Dimension(280, 50));

        lblupphoto2.setBackground(new java.awt.Color(255, 51, 255));
        lblupphoto2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lblupphoto2.setForeground(new java.awt.Color(102, 0, 102));
        lblupphoto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblupphoto2.setText("To View Form ");
        lblupphoto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblupphoto2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblupphoto2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblupphoto2.setOpaque(true);
        lblupphoto2.setPreferredSize(new java.awt.Dimension(280, 50));

        btnform.setBackground(new java.awt.Color(255, 51, 255));
        btnform.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnform.setForeground(new java.awt.Color(102, 0, 102));
        btnform.setText("CLICK HERE");
        btnform.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        btnform.setPreferredSize(new java.awt.Dimension(150, 50));
        btnform.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnformActionPerformed(evt);
            }
        });

        btnphoto.setBackground(new java.awt.Color(255, 51, 255));
        btnphoto.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnphoto.setForeground(new java.awt.Color(102, 0, 102));
        btnphoto.setText("CLICK HERE");
        btnphoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        btnphoto.setPreferredSize(new java.awt.Dimension(150, 50));
        btnphoto.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnphotoActionPerformed(evt);
            }
        });

        btnpass.setBackground(new java.awt.Color(255, 51, 255));
        btnpass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnpass.setForeground(new java.awt.Color(102, 0, 102));
        btnpass.setText("CLICK HERE");
        btnpass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        btnpass.setPreferredSize(new java.awt.Dimension(150, 50));
        btnpass.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnpassActionPerformed(evt);
            }
        });

        btnview.setBackground(new java.awt.Color(255, 51, 255));
        btnview.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnview.setForeground(new java.awt.Color(102, 0, 102));
        btnview.setText("CLICK HERE");
        btnview.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        btnview.setPreferredSize(new java.awt.Dimension(150, 50));
        btnview.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnldataLayout = new javax.swing.GroupLayout(pnldata);
        pnldata.setLayout(pnldataLayout);
        pnldataLayout.setHorizontalGroup(
            pnldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnldataLayout.createSequentialGroup()
                        .addComponent(lblchpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnldataLayout.createSequentialGroup()
                        .addComponent(lblupphoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnphoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnldataLayout.createSequentialGroup()
                        .addComponent(lblupphoto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnldataLayout.createSequentialGroup()
                        .addComponent(lblupphoto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnldataLayout.setVerticalGroup(
            pnldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldataLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(pnldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblupphoto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(pnldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblupphoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnphoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblchpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblupphoto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        lblupphoto.getAccessibleContext().setAccessibleName("");

        pnlframe.add(pnldata);
        pnldata.setBounds(19, 105, 492, 464);

        lblwelcome.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        lblwelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblwelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblwelcome.setText("WELCOME");
        pnlframe.add(lblwelcome);
        lblwelcome.setBounds(19, 15, 750, 70);
        pnlframe.add(lblpnl);
        lblpnl.setBounds(0, 0, 900, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlframe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlframe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnpassActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnpassActionPerformed
    {//GEN-HEADEREND:event_btnpassActionPerformed
        new ResetPassword(ref,"return to menu").setVisible(true);
        thrstop = false;
        dispose();
    }//GEN-LAST:event_btnpassActionPerformed

    private void btnformActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnformActionPerformed
    {//GEN-HEADEREND:event_btnformActionPerformed
         try
        {
            Connection co = DriverManager.getConnection("jdbc:mysql://localhost:3306/database","root","root");
            Statement stm = co.createStatement();
            String qu = "Select * from database.formdata where user = '" + ref + "'";
            ResultSet rs;
            rs = stm.executeQuery(qu);
            if(rs.next())
            {
                JOptionPane.showMessageDialog(null, "Details already Exists");
            }
            else
            {
                new FillForm(ref).setVisible(true);
                thrstop = false;
                dispose();
            }
        }
        catch (SQLException ex)
        {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnformActionPerformed

    private void lbllogoutMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbllogoutMouseClicked
    {//GEN-HEADEREND:event_lbllogoutMouseClicked
        int res = JOptionPane.showConfirmDialog(null, "Are You Sure You Want To LOGOUT?","LOGOUT USER",JOptionPane.YES_NO_CANCEL_OPTION);
        if(res == JOptionPane.YES_OPTION)
        {
            new LoginFrame().setVisible(true);
            thrstop = false;
            dispose();
            JOptionPane.showMessageDialog(null, "LOGGED OUT SUCCESSFULLY");
        }
    }//GEN-LAST:event_lbllogoutMouseClicked

    private void btnphotoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnphotoActionPerformed
    {//GEN-HEADEREND:event_btnphotoActionPerformed
        try
        {
            Connection co = DriverManager.getConnection("jdbc:mysql://localhost:3306/database","root","root");
            Statement stm = co.createStatement();
            String qu = "Select * from database.photodata where user = '" + ref + "'";
            ResultSet rs;
            rs = stm.executeQuery(qu);
            if(rs.next())
            {
                JOptionPane.showMessageDialog(null, "Photos already Uploaded");
            }
            else
            {
                new UploadPhoto(ref).setVisible(true);
                thrstop = false;
                dispose();
            }
        }
        catch (SQLException ex)
        {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnphotoActionPerformed

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnviewActionPerformed
    {//GEN-HEADEREND:event_btnviewActionPerformed
        new DisplayForm(ref).setVisible(true);
        thrstop = false;
        dispose();
    }//GEN-LAST:event_btnviewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MenuClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MenuClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MenuClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MenuClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MenuClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnform;
    private javax.swing.JButton btnpass;
    private javax.swing.JButton btnphoto;
    private javax.swing.JButton btnview;
    private javax.swing.JLabel lblchpass;
    private javax.swing.JLabel lbllogout;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblpnl;
    private javax.swing.JLabel lblprofilephoto;
    private javax.swing.JLabel lblsignature;
    private javax.swing.JLabel lblupphoto;
    private javax.swing.JLabel lblupphoto1;
    private javax.swing.JLabel lblupphoto2;
    private javax.swing.JLabel lblwelcome;
    private javax.swing.JPanel pnldata;
    private javax.swing.JPanel pnlframe;
    private javax.swing.JPanel pnlphoto;
    // End of variables declaration//GEN-END:variables
}
